# ⭐ **SVM (Support Vector Machine)**

SVM is a **powerful Machine Learning algorithm** used for **classification** and **regression** tasks.
Its main goal is to find the **best possible boundary** (called a **hyperplane**) that separates different classes of data.
It chooses the boundary with the **maximum margin** — the line that stays farthest from the closest data points.
These closest points are called **support vectors**. 🎯

---

# ⭐ **Types of SVM**

## **1. Linear SVM** ➖

Used when data can be separated with a **straight line**.
Simple, fast, and works well when classes are clearly separated.

---

## **2. Non-Linear SVM** 🔄

Used when data **cannot** be separated by a straight line.
SVM uses **kernel functions** to transform data into a higher dimension to make separation easier.

### **Kernel Types:**

### **a) Polynomial Kernel** 🔺

Creates curved or complex boundaries.
Useful when features have a polynomial relationship.

### **b) RBF (Gaussian) Kernel** 🌐

Most popular kernel.
Creates smooth and flexible boundaries and works well with complex patterns.

### **c) Sigmoid Kernel** 📈

Works similar to a neural network activation function.

---

## **3. SVM for Classification** 🧩

SVM supports:

* **Binary classification** (2 classes)
* **Multi-class classification** (more than 2 classes)

---

## **4. Support Vector Regression (SVR)** 📊

Regression version of SVM.
Instead of separating classes, SVR fits a line or curve within a **margin of error** to predict continuous values.


In [13]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ml libraries
from sklearn.svm import SVC

# for model selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder


In [15]:
# import the data
df = sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [17]:
# let's make X and y in data
X = df.drop('species', axis=1)
y = df['species']

In [19]:
# train test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [20]:
# call the model and train the model
model = SVC()

# train the model
model.fit(X_train, y_train)

# predict the model 
y_pred = model.predict(X_test)

In [25]:
# evaluate the model 
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[16  0  0]
 [ 0  6  0]
 [ 0  0  8]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        16
  versicolor       1.00      1.00      1.00         6
   virginica       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

