**Naive Bayes**:

---

## **What is Naive Bayes?**

**Naive Bayes** is a **machine learning algorithm** used for **classification tasks**.
It is called “Naive” because it **assumes that all features are independent** of each other — which is a simplification, but it works surprisingly well in practice ✅.

---

### **Key Points**

1. **Probabilistic Model** 📊

   * It calculates the probability of each class based on the features.
   * Predicts the class with **highest probability**.

2. **Types of Naive Bayes**:

   * **GaussianNB** → For numeric data (like age, salary)
   * **MultinomialNB** → For count data (like word counts in text)
   * **BernoulliNB** → For binary features (yes/no, 0/1)

3. **Advantages** ✅

   * Very fast and simple
   * Works well with large datasets
   * Performs surprisingly well even if the independence assumption is not true

4. **Disadvantages** ⚠️

   * Assumes feature independence (not always true)
   * Doesn’t capture interactions between features

---

### **Example Use Case**

* Email **spam detection** 📨
* Job salary classification 💼
* Text sentiment analysis 😀😡

---
- **GaussianNB** → numeric features ke liye best
- **MultinomialNB** → text/count features ke liye
- **BernoulliNB** → binary features ke liye



In [2]:
# import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris


In [3]:
# load the dataset
iris = load_iris()
X = iris.data
y = iris.target

# train test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



1. **Gaussian Naive Bayes (GaussianNB)**
   - Used for **numeric features**.
   - Assumes that the features follow a **normal (Gaussian) distribution**.
   - Example: Age, Salary, Height, Weight.

In [ ]:
# Gaussian Naive Bayes (GaussianNB)
gnb = GaussianNB()

# train the model
gnb.fit(X_train, y_train)

# predict the model
y_pred = gnb.predict(X_test)

# evalate the model
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification Report: \n{classification_report(y_test, y_pred)}")


Accuracy: 1.0
Confusion Matrix: 
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



2. **Multinomial Naive Bayes (MultinomialNB)**
   - Used for **count data** or **frequency-based features**.
   - Commonly used in **text classification** (e.g., word counts in documents).
   - Example: Document classification, spam detection.

In [ ]:
# Multinomial Naive Bayes (MultinomialNB)
mnb = MultinomialNB()

# train the model
mnb.fit(X_train, y_train)

# predict the model
y_pred = mnb.predict(X_test)

# evalate the model
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification Report: \n{classification_report(y_test, y_pred)}")

#

Accuracy: 0.9
Confusion Matrix: 
[[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



3. **Bernoulli Naive Bayes (BernoulliNB)**
   - Used for **binary/boolean features** (0/1, yes/no).
   - Example: Whether a word occurs in a document or not.


In [6]:
# Bernoulli Naive Bayes (BernoulliNB)
bnb = BernoulliNB()

# train the model
bnb.fit(X_train, y_train)

# predict the model
y_pred = bnb.predict(X_test)

# evalate the model
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}")
print(f"Classification Report: \n{classification_report(y_test, y_pred)}")


Accuracy: 0.3
Confusion Matrix: 
[[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
Classification Report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
